/**
 * Generated by scripts/fetch-starter-covers.ts — do not edit by hand.
 *
 * Maps starter-shelf IGDB ids to locally-served cover art under public/assets/starter/. Used by
 * `getStarterSet` (lib/games/repo.ts) to swap the remote images.igdb.com URL for a same-origin
 * path, so the pool builder opens with no external-CDN cover loading. Covers are the `t_cover_big_2x`
 * size, matching the rest of the app. Re-run the script if the starter shelf changes.
 */
export const STARTER_COVERS: Record<number, string> = {
  // The Witcher 3: Wild Hunt
  1942: '/assets/starter/the-witcher-3-wild-hunt.jpg',
  // Elden Ring
  119133: '/assets/starter/elden-ring.jpg',
  // The Legend of Zelda: Breath of the Wild
  237895: '/assets/starter/the-legend-of-zelda-breath-of-the-wild.jpg',
  // Hades
  113112: '/assets/starter/hades.jpg',
  // Animal Crossing: New Horizons
  109462: '/assets/starter/animal-crossing-new-horizons.jpg',
  // Resident Evil 2
  19686: '/assets/starter/resident-evil-2.jpg',
  // The Last of Us
  1009: '/assets/starter/the-last-of-us.jpg',
  // Doom Eternal
  103298: '/assets/starter/doom-eternal.jpg',
  // The Binding of Isaac: Rebirth
  7789: '/assets/starter/the-binding-of-isaac-rebirth.jpg',
  // Persona 5 Royal
  114283: '/assets/starter/persona-5-royal.jpg',
  // Forza Horizon 5
  141503: '/assets/starter/forza-horizon-5.jpg',
  // Sid Meier's Civilization VI
  19130: '/assets/starter/sid-meier-s-civilization-vi.jpg',
  // Portal 2
  72: '/assets/starter/portal-2.jpg',
  // The Elder Scrolls 5: Skyrim
  472: '/assets/starter/the-elder-scrolls-5-skyrim.jpg',
  // Bloodborne
  7334: '/assets/starter/bloodborne.jpg',
  // Super Mario 64
  1074: '/assets/starter/super-mario-64.jpg',
  // Hollow Knight
  14593: '/assets/starter/hollow-knight.jpg',
  // Minecraft
  135400: '/assets/starter/minecraft.jpg',
  // Silent Hill 2
  222341: '/assets/starter/silent-hill-2.jpg',
  // God of War
  19560: '/assets/starter/god-of-war.jpg',
  // Half-Life 2
  233: '/assets/starter/half-life-2.jpg',
  // Slay the Spire
  40477: '/assets/starter/slay-the-spire.jpg',
  // Final Fantasy 7
  427: '/assets/starter/final-fantasy-7.jpg',
  // Mario Kart 8
  2350: '/assets/starter/mario-kart-8.jpg',
  // Crusader Kings 3
  124954: '/assets/starter/crusader-kings-3.jpg',
  // Limbo
  1331: '/assets/starter/limbo.jpg',
  // Baldur's Gate 3
  119171: '/assets/starter/baldur-s-gate-3.jpg',
  // Sekiro: Shadows Die Twice
  76882: '/assets/starter/sekiro-shadows-die-twice.jpg',
  // Stardew Valley
  17000: '/assets/starter/stardew-valley.jpg',
  // Amnesia: The Dark Descent
  111: '/assets/starter/amnesia-the-dark-descent.jpg',
  // Red Dead Redemption 2
  25076: '/assets/starter/red-dead-redemption-2.jpg',
  // Dead Cells
  26855: '/assets/starter/dead-cells.jpg',
  // NieR: Automata
  11208: '/assets/starter/nier-automata.jpg',
  // Rocket League
  11198: '/assets/starter/rocket-league.jpg',
  // XCOM 2
  10919: '/assets/starter/xcom-2.jpg',
  // Inside
  7342: '/assets/starter/inside.jpg',
};
